<a href="https://colab.research.google.com/github/VimanAndrei/jupyter_notebook/blob/main/ProiectLab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.	Codificati propozitiile “To be or not to be? that is the question.”, “But, to know a man well, were to know himself.”, “Knowing yourself is the beginning of all wisdom.”, “To know yourself is to know others.” utilizand reprezentarile de tip:

> a. Bag of Words

> b. Term Frequency-Inverse Document Frequency

2.	Afisati codificarile fiecareia din propozitiile de mai sus atat utilizand BOW cat si TF-IDF, ce se observa?
3.	Codificati aceleasi propozitii de mai sus utilizand bag of n grams si afisati vocabularul impreuna cu codificarile pentru fiecare propozitie.


In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import sklearn as sk
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
corpus = [
    'To be or not to be? that is the question.',
    'But, to know a man well, were to know himself.',
    'Knowing yourself is the beginning of all wisdom.',
    'To know yourself is to know others.'
    ]

In [ ]:
vectorizer = CountVectorizer()

In [ ]:
X = vectorizer.fit_transform(corpus)

In [ ]:
vectorizer.get_feature_names_out()

array(['all', 'be', 'beginning', 'but', 'himself', 'is', 'know',
       'knowing', 'man', 'not', 'of', 'or', 'others', 'question', 'that',
       'the', 'to', 'well', 'were', 'wisdom', 'yourself'], dtype=object)

In [ ]:
print(X.toarray())

[[0 2 0 0 0 1 0 0 0 1 0 1 0 1 1 1 2 0 0 0 0]
 [0 0 0 1 1 0 2 0 1 0 0 0 0 0 0 0 2 1 1 0 0]
 [1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 1 1]
 [0 0 0 0 0 1 2 0 0 0 0 0 1 0 0 0 2 0 0 0 1]]


In [ ]:
pd.DataFrame(X.A, columns=vectorizer.get_feature_names_out())

all  be  beginning  but  himself  is  know  knowing  man  not  ...  or  \
0    0   2          0    0        0   1     0        0    0    1  ...   1   
1    0   0          0    1        1   0     2        0    1    0  ...   0   
2    1   0          1    0        0   1     0        1    0    0  ...   0   
3    0   0          0    0        0   1     2        0    0    0  ...   0   

   others  question  that  the  to  well  were  wisdom  yourself  
0       0         1     1    1   2     0     0       0         0  
1       0         0     0    0   2     1     1       0         0  
2       0         0     0    1   0     0     0       1         1  
3       1         0     0    0   2     0     0       0         1  

[4 rows x 21 columns]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorizer2 = TfidfVectorizer()

In [ ]:
X1 = vectorizer2.fit_transform(corpus) 

In [ ]:
vectorizer2.get_feature_names_out()

array(['all', 'be', 'beginning', 'but', 'himself', 'is', 'know',
       'knowing', 'man', 'not', 'of', 'or', 'others', 'question', 'that',
       'the', 'to', 'well', 'were', 'wisdom', 'yourself'], dtype=object)

In [ ]:
print(X1.toarray())

[[0.         0.61260284 0.         0.         0.         0.19550823
  0.         0.         0.         0.30630142 0.         0.30630142
  0.         0.30630142 0.30630142 0.24149156 0.39101646 0.
  0.         0.         0.        ]
 [0.         0.         0.         0.33120551 0.33120551 0.
  0.52225246 0.         0.33120551 0.         0.         0.
  0.         0.         0.         0.         0.42280837 0.33120551
  0.33120551 0.         0.        ]
 [0.387766   0.         0.387766   0.         0.         0.24750601
  0.         0.387766   0.         0.         0.387766   0.
  0.         0.         0.         0.30571917 0.         0.
  0.         0.387766   0.30571917]
 [0.         0.         0.         0.         0.         0.25748655
  0.63609424 0.         0.         0.         0.         0.
  0.40340244 0.         0.         0.         0.51497311 0.
  0.         0.         0.31804712]]


In [ ]:
pd.DataFrame(np.round(X1.A,2), columns=vectorizer2.get_feature_names_out())

all    be  beginning   but  himself    is  know  knowing   man   not  ...  \
0  0.00  0.61       0.00  0.00     0.00  0.20  0.00     0.00  0.00  0.31  ...   
1  0.00  0.00       0.00  0.33     0.33  0.00  0.52     0.00  0.33  0.00  ...   
2  0.39  0.00       0.39  0.00     0.00  0.25  0.00     0.39  0.00  0.00  ...   
3  0.00  0.00       0.00  0.00     0.00  0.26  0.64     0.00  0.00  0.00  ...   

     or  others  question  that   the    to  well  were  wisdom  yourself  
0  0.31     0.0      0.31  0.31  0.24  0.39  0.00  0.00    0.00      0.00  
1  0.00     0.0      0.00  0.00  0.00  0.42  0.33  0.33    0.00      0.00  
2  0.00     0.0      0.00  0.00  0.31  0.00  0.00  0.00    0.39      0.31  
3  0.00     0.4      0.00  0.00  0.00  0.51  0.00  0.00    0.00      0.32  

[4 rows x 21 columns]

In [ ]:
vectorizer3 = CountVectorizer(analyzer='word', ngram_range=(2, 2))

In [ ]:
X2 = vectorizer3.fit_transform(corpus)

In [ ]:
vectorizer3.get_feature_names_out()

array(['all wisdom', 'be or', 'be that', 'beginning of', 'but to',
       'is the', 'is to', 'know himself', 'know man', 'know others',
       'know yourself', 'knowing yourself', 'man well', 'not to',
       'of all', 'or not', 'that is', 'the beginning', 'the question',
       'to be', 'to know', 'well were', 'were to', 'yourself is'],
      dtype=object)

In [ ]:
print(X2.toarray())

[[0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1 2 0 0 0 0]
 [0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 2 1 1 0]
 [1 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 2 0 0 1]]


In [ ]:
pd.DataFrame(X2.A, columns=vectorizer3.get_feature_names_out())

all wisdom  be or  be that  beginning of  but to  is the  is to  \
0           0      1        1             0       0       1      0   
1           0      0        0             0       1       0      0   
2           1      0        0             1       0       1      0   
3           0      0        0             0       0       0      1   

   know himself  know man  know others  ...  of all  or not  that is  \
0             0         0            0  ...       0       1        1   
1             1         1            0  ...       0       0        0   
2             0         0            0  ...       1       0        0   
3             0         0            1  ...       0       0        0   

   the beginning  the question  to be  to know  well were  were to  \
0              0             1      2        0          0        0   
1              0             0      0        2          1        1   
2              1             0      0        0          0        0   
3              0             0      0        2          0        0   

   yourself is  
0            0  
1            0  
2            1  
3            1  

[4 rows x 24 columns]